spring.application.name=online-auction-api
spring.profiles.active=postgres

#Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE
logging.level.com.auction=DEBUG

#jwt
jwt.secret=your-super-secret-key-change-this-in-production-min-32-chars!!
jwt.access-token-expiry=604800000
jwt.refresh-token-expiry=604800000
