spring.application.name=travel-booking-api

#Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE
logging.level.com.auction=DEBUG

#H2
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always

#jwt
jwt.secret=your-super-secret-key-change-this-in-production-min-32-chars!!
jwt.access-token-expiry=604800000
jwt.refresh-token-expiry=604800000
